version: '3.9'

x-cert-volume:
  &cert-volume
  type: bind
  source: ./certs/
  target: /etc/ssl/certs/

services:
  cats-service:
    build: ./cats-service/
  dogs-service:
    build: ./dogs-service/

  envoy-gateway:
    image: envoyproxy/envoy-dev:58deeb0b2c814b5cd66c32d7f4135dc92305439a
    ports:
      - "8000:10000"
    volumes:
      - <<: *cert-volume
      - ./envoy/config.yaml:/etc/envoy/envoy.yaml

  kong-gateway:
    image: kong/kong-gateway:2.8.1.1-alpine
    ports:
      - "8001:8443"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/config.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_SSL=on
      - KONG_SSL_CERT=/etc/ssl/certs/server_cert.pem
      - KONG_SSL_CERT_KEY=/etc/ssl/certs/server_key.pem
    volumes:
      - <<: *cert-volume
      - ./kong/config.yml:/kong/declarative/config.yml

  krakend-gateway:
    image: devopsfaith/krakend
    ports:
      - "8002:8443"
    volumes:
      - <<: *cert-volume
      - ./krakend/krakend.json:/etc/krakend/krakend.json

  nginx-gateway:
    image: nginx:latest
    ports:
      - "8003:443"
    volumes:
      - <<: *cert-volume
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
