apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: hello-kube
spec:
  parentRefs:
    - name: eg
  # hostnames:
  #   - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: hello-kube
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
