version: '3'
services:
  nginx-gateway:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  cats-service:
    build: ../cats-service/
  dogs-service:
    build: ../dogs-service/
